#!/usr/bin/env bash

export TERMINAL=terminator

[[ -z $1 || ! -e $1 ]] &&
	exit 1

mime_type="$(file -b --mime-type "$1")"

case "$mime_type" in
	text/html|text/xml|application/x-mimearchive|message/rfc822)
			select ops in exit weaver $BROWSER vimb chromium firefox w3m links elinks $EDITOR; do
			[[ $ops = exit ]] && exit
			[[ $ops = w3m || $ops = links || $ops = elinks || $EDITOR ]] && $TERMINAL -x "$ops" "$1" &
			"$ops" "$1" &> /dev/null &
		done
	;;

	text/*|*/xml|application/x-httpd-php3|application/x-httpd-php4|application/x-httpd-php5|application/x-shellscript)
		$TERMINAL -x "${VISUAL:-${EDITOR:-vis}}" "$@"
	;;

	image/*)
		select ops in exit sxiv feh mtpaint gifview gimp; do
			[[ $ops = exit ]] && exit
			[[ $ops = gifview ]] && gifview -a "$1" &
			"$ops" "$1" &> /dev/null &
		done
	;;

	video/*|application/x-matroska)
		select ops in exit mpv vlc cvlc ffplay ffprobe mediainfo mplayer; do
			[[ $ops = exit ]] && exit
			[[ $ops = mpv ]] && mpv --player-operation-mode=pseudo-gui -- "$1" &
			"$ops" "$1" &
		done
	;;

	audio/*| application/ogg|application/x-ogg|application/mxf|application/sdp|application/smil|application/x-smil|application/streamingmedia|application/x-streamingmedia|application/vnd.rn-realmedia|application/vnd.rn-realmedia-vbr)
		select ops in exit mpv vlc cvlc ffplay ffprobe soxi mediainfo mpg123 mplayer; do
			[[ $ops = exit ]] && exit
			[[ $ops = mpv ]] && mpv --player-operation-mode=pseudo-gui -- "$1" &
			"$ops" "$1" &
		done
	;;

	application/pdf|application/x-pdf|application/x-cbz|applilcation/oxps|application/vnd.ms-xpsdocument)
		select ops in exit mupdf xournalpp pdfinfo xreader evince zathura qpdfview; do
			[[ $ops = exit ]] && exit
			$ops "$1" &
		done
	;;
	application/octet-stream)
		case "$1" in
			*.chm|*.CHM) 
				select ops in exit kchmviewer xchm chmopen; do
					[[ $ops = exit ]] && exit
					$ops "$1" &
				done
			;;
			*.gpg)
				gpg -d "$1"
			;;
			*)
				echo "unknow filetype"
			;;
		esac
	;;
	application/vnd.ms-htmlhelp)
		select ops in exit kchmviewer xchm chmopen; do
			[[ $ops = exit ]] && exit
			$ops "$1" &
		done
	;;

	application/vnd.comicbook*)
		select ops in exit mupdf foliate; do
			[[ $ops = exit ]] && exit
			$ops "$1" &
		done
	;;

	application/epub+zip|application/x-mobipocket-ebook)
		select ops in exit epy mupdf foliate; do
			case $ops in
				exit) exit ;;
				epy) terminator -p Large -x epy.py "$1" ;;
				*) $ops "$1" &> /dev/null & ;;
			esac
		done
	;;

	application/pgp-encrypted)
		gpg -d "$1"
	;;

	application/*zip*|application/x-?ar|application/x-?z)
		case "$1" in
			*.xoj|*.xopp) xournalpp "$1" &> /dev/null ;;
			*.cb?) 
				select ops in exit mupdf foliate als unar; do
					[[ $ops = exit ]] && exit
					[[ $ops = als || $ops = unar ]] && "$ops" "$1"
					"$ops" "$1" &> /dev/null &
				done
			;;
			*)
				select ops in exit als lsar unar aunpack; do
					[[ $ops = exit ]] && exit
					[[ $ops = aunpack ]] && aunpack -D "$1"
					"$ops" "$1"
				done
			;;
		esac
	;;

	*opendocument*|*openxmlformats*|*msword|*ms-excel|*ms-powerpoint|*abiword|*write*)
		libreoffice "$1" --norestore &> /dev/null
	;;

	inode/directory)
		select ops in exit nnn vifm pcmanfm thunar ranger nautilus; do
			[[ $ops = exit ]] && exit
			$ops "$1"
		done
	;;

	inode/x-empty)
		echo "empty file"
		rm -i "$1"
	;;

	*) 
		case "$@" in
			*) echo "no filetype association for $@" ;;
		esac
	;;
esac
